# golangci-lint configuration
version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - misspell
    - gosec
    - gocritic

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false

    govet:
      enable-all: true
      disable:
        - shadow

    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - hugeParam
        - rangeValCopy

    revive:
      rules:
        - name: exported
          disabled: false
        - name: unexported-return
          disabled: true
        - name: blank-imports
          disabled: false

    misspell:
      locale: US

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
