linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/willibrandon/mtlog-audit

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - hugeParam
      - rangeValCopy

  revive:
    rules:
      - name: exported
        disabled: false
      - name: unexported-return
        disabled: true
      - name: blank-imports
        disabled: false

  misspell:
    locale: US

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - revive
    - misspell
    - unconvert
    - gosec
    - gocritic

  disable:
    - typecheck  # Disabled due to Go 1.24+ compatibility

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - examples

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude test files from certain linters
    - path: _test\.go
      linters:
        - gosec
        - errcheck

    # Exclude generated files
    - path: \.pb\.go$
      linters:
        - all
