# golangci-lint configuration
version: 2

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - hugeParam
      - rangeValCopy

  revive:
    rules:
      - name: exported
        disabled: false
      - name: unexported-return
        disabled: true
      - name: blank-imports
        disabled: false

  misspell:
    locale: US

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - misspell
    - gosec
    - gocritic

run:
  timeout: 5m
  tests: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude test files from certain linters
    - path: _test\.go
      linters:
        - gosec
        - errcheck

    # Exclude generated files
    - path: \.pb\.go$
      linters:
        - all
